### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by TangXing** [metarank/lightgbm4j#28]
java.lang.UnsatisfiedLinkError: C:XXXXX\AppData\Local\Temp\lightgbm_swig_7065972505607761555.bin: Can't find dependent libraries

**Comment by shuttie** [comment]
I was able to reproduce the issue on clear win10 install. But I guess it's related to the upstream LightGBM build of the `lib_lightgbm.dll`, as this project just repackages this file as is. 
You can use a https://github.com/lucasg/Dependencies tool to see what's wrong with this file on your system, but probably it will complain on missing symbols from `WS2_32.dll`: 
![image](https://user-images.githubusercontent.com/999061/101245710-8f64a000-3706-11eb-8da4-8c29d6bf373d.png)

Unfortunately I'm not able to propose any fixes on this issue. But you can re-open this issue on a LightGBM repo with a more detailed description.

**Comment by jinhanlai** [comment]
I fixed this problem in macos/Linux. You can regenerate the dll file through this link(https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#id21), and then find the **.dylib file in the generated build directory to overwrite src/resources/mac/x86_64/**.dylib

**Comment by shuttie** [comment]
@TangXing fixed in 3.2.0-2
