### ISSUE TITLE
java: Inaccessible io.github.metarank.lightgbm4j.LGBMBooster

### ISSUE THREAD

**Issue by jinhanlai** [metarank/lightgbm4j#33]
Hi, I am trying to use lightgbm4j  with Java 8 + maven :
I am using Mac OS, but when I compile the project I get the error below:

Error:(2, 37) java: Inaccessible  io.github.metarank.lightgbm4j.LGBMBooster
  Wrong class file: /Users/*/ProgramData/apache-maven-3.6.3/repository/io/github/metarank/lightgbm4j/3.1.1-1/lightgbm4j-3.1.1-1.jar!/io/github/metarank/lightgbm4j/LGBMBooster.class
    The class file has the wrong version 55.0, should be 52.0

**Comment by shuttie** [comment]
Should be fixed by https://github.com/metarank/lightgbm4j/commit/723dba1fa989a2046f6cd1c8fe1a6486e9341a45

You can try version `3.1.1-2` which is now java8-compatible. But anyway, I guess it's time to switch to 11 LTS :)

**Comment by jinhanlai** [comment]
In macos, this file directory does not exist, the mac directory should be written as osx.
![image](https://user-images.githubusercontent.com/53830087/102032873-e9dfb980-3df4-11eb-8c67-b4d9b3ee1173.png)

**Comment by shuttie** [comment]
@jinhanlai please try the https://github.com/metarank/lightgbm4j/releases/tag/3.1.1-3
I also have a ticket to run the CI on mac/windows to prevent these types of issues here: #36

**Comment by shuttie** [comment]
fixed in 3.2.0-2
