### ISSUE TITLE
Impossible to train after CreateFromMat

### ISSUE THREAD

**Issue by TBrb** [metarank/lightgbm4j#38]
Thank you for all the work on this very useful library !

I was able to train a model with the CreateFromFile method but not with CreateFromMat.
Do you have an example of training and prediction with data from CreateFromMat method ? 

The problem may be related to the parameter label_column working only in case of loading data directly from file according to the documentation.

**Comment by shuttie** [comment]
@TBrb should be fixed in the next release. TLDR: label field is magical and cannot be set only by using `createFromMat` call, you need to explicitly call `setField` for it. I've updated docs and added an example+test to show how it works.

**Comment by shuttie** [comment]
Fixed in https://github.com/metarank/lightgbm4j/releases/tag/3.1.1-4

**Comment by TBrb** [comment]
Thank you @shuttie , it works well now :) !
