### ISSUE TITLE
Problem native library

### ISSUE THREAD

**Issue by TBrb** [metarank/lightgbm4j#42]
Hi Shuttie,

Again, many thanks for this very useful library.

We have the following problem
https://github.com/microsoft/LightGBM/issues/2742#issuecomment-797402773

But it is already corrected in the last source files :) (We built locally and it solved this problem).
Is it possible to update lightgbm4j to have the latest sources ?

**Comment by shuttie** [comment]
I'm not sure that it's a good idea to have a public unstable snapshot build of LightGBM binary in maven. But you can solve it by yourself, if you really need the snapshot build.

This thing takes the native libraries out of the jar resources from https://github.com/metarank/lightgbm4j/tree/main/src/main/resources. As resources are global to the ClassLoader (and in a simple case - they are global to the whole classpath) and taken in an explicit order, then you can do the following trick:
* build a native library for your platform of choice.
* create a `./src/main/resources/<platform>/x86_64` dir in your app
* put the freshly-built native library there. Make sure that the name matches the one in the original lightgbm4j resources folder.

Then [the native lib loader](https://github.com/metarank/lightgbm4j/blob/48649a766a1f018b2063c7062a5fe27c9b29ba80/src/main/java/io/github/metarank/lightgbm4j/LGBMBooster.java#L39) will prefer your binary to the one in the jar file, and it should work as-is.

**Comment by shuttie** [comment]
@TBrb Luckily LightGBM released a new shiny 3.2.0 version, so you can try the new build: https://github.com/metarank/lightgbm4j/releases/tag/3.2.0-1. I've published it to maven-central already.

**Comment by shuttie** [comment]
I'm closing the ticket as fixed, but if the problem persists - don't hesitate to reopen it.

**Comment by TBrb** [comment]
Hi Shuttie,

Sorry for the delay and many thanks for the new release !

I would like to help and contribute to the project, do you have priorities / road map ?
