### ISSUE TITLE
Does it support the 'pred_leaf' function of lightgbm?

### ISSUE THREAD

**Issue by ToUranus** [metarank/lightgbm4j#59]
When I use lightgbm, I not only want to predict the classification result and probability value of the instance, I want to get the binary features of the tree model, which is convenient for the subsequent input of the logistic regression algorithm (GBDT+LR), so I want to ask if there are parameters similar to extracting native the 'pred_leaf' parameter in the lightgbm interface.thanks for your answer

**Comment by shuttie** [comment]
Are you talking about this method: https://lightgbm.readthedocs.io/en/latest/C-API.html#c.LGBM_BoosterGetLeafValue ?

**Comment by ToUranus** [comment]
no，this method：https://lightgbm.readthedocs.io/en/latest/Parameters.html?highlight=predict#predict-parameters

parameter:   predict_leaf_index

just in predictict params, I want to get every predictions are in which leaf(leaf index).

**Comment by ToUranus** [comment]
> Are you talking about this method: https://lightgbm.readthedocs.io/en/latest/C-API.html#c.LGBM_BoosterGetLeafValue ?

no，this method：https://lightgbm.readthedocs.io/en/latest/Parameters.html?highlight=predict#predict-parameters

parameter: predict_leaf_index

just in predictict params, I want to get every predictions are in which leaf(leaf index).
